"""live mode data source

Revision ID: 0f3de7537fad
Revises: a8c5a409897f
Create Date: 2026-09-04 22:38:21.795646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3de7537fad'
down_revision: Union[str, Sequence[str], None] = 'a8c5a409897f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)

    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)

    with op.batch_alter_table('index_bars', schema=None) as batch_op:
        batch_op.alter_column('index_code',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)

    with op.batch_alter_table('indices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=8), nullable=False, server_default='replay'))
        batch_op.add_column(sa.Column('instrument_key', sa.String(length=64), nullable=True))
        batch_op.alter_column('index_code',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_indices_source'), ['source'], unique=False)

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)

    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=8), nullable=False, server_default='replay'))
        batch_op.add_column(sa.Column('instrument_key', sa.String(length=64), nullable=True))
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)
        batch_op.alter_column('sector_index',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_symbols_source'), ['source'], unique=False)

    # source joins the primary key, so the table is rebuilt rather than
    # altered: autogenerate does not detect a key change, and batch mode cannot
    # override the key it reflects. Copy-and-swap works on SQLite and Postgres
    # alike. Existing rows are the fixture's calendar, hence 'replay'.
    op.rename_table('trading_days', 'trading_days_old')
    op.create_table(
        'trading_days',
        sa.Column('day', sa.Date(), nullable=False),
        sa.Column('source', sa.String(length=8), nullable=False, server_default='replay'),
        sa.Column('close_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('day', 'source'),
    )
    op.execute(
        "INSERT INTO trading_days (day, source, close_at) "
        "SELECT day, 'replay', close_at FROM trading_days_old"
    )
    op.drop_table('trading_days_old')

    with op.batch_alter_table('user_symbol_anchor', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_source', sa.String(length=8), nullable=False, server_default='replay'))

    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)

    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('data_source')

    with op.batch_alter_table('user_symbol_anchor', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    op.rename_table('trading_days', 'trading_days_new')
    op.create_table(
        'trading_days',
        sa.Column('day', sa.Date(), nullable=False),
        sa.Column('close_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('day'),
    )
    op.execute(
        "INSERT INTO trading_days (day, close_at) "
        "SELECT day, close_at FROM trading_days_new WHERE source = 'replay'"
    )
    op.drop_table('trading_days_new')

    with op.batch_alter_table('symbols', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symbols_source'))
        batch_op.alter_column('sector_index',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('instrument_key')
        batch_op.drop_column('source')

    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('indices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indices_source'))
        batch_op.alter_column('index_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('instrument_key')
        batch_op.drop_column('source')

    with op.batch_alter_table('index_bars', schema=None) as batch_op:
        batch_op.alter_column('index_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('daily_bars', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.alter_column('symbol',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
