"""simulation state

Revision ID: a8c5a409897f
Revises: b1a573c914fc
Create Date: 2026-09-04 17:51:08.694848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c5a409897f'
down_revision: Union[str, Sequence[str], None] = 'b1a573c914fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_state',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.DateTime(), nullable=True),
    sa.Column('anchor_sessions_ago', sa.Integer(), nullable=True),
    sa.Column('freshness_json', sa.Text(), nullable=False),
    sa.Column('scenario', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_state')
    # ### end Alembic commands ###
