"""initial schema

Revision ID: b1a573c914fc
Revises: 
Create Date: 2026-09-04 17:44:52.014804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a573c914fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_bars',
    sa.Column('index_code', sa.String(length=16), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('index_code', 'day')
    )
    op.create_table('indices',
    sa.Column('index_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_market', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('index_code')
    )
    op.create_table('symbols',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sector_index', sa.String(length=16), nullable=True),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('listed_on', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('trading_days',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('close_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_open_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('corporate_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'occurred_on', 'kind', name='uq_event_identity')
    )
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_events_symbol'), ['symbol'], unique=False)

    op.create_table('daily_bars',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.PrimaryKeyConstraint('symbol', 'day')
    )
    op.create_table('quotes',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('freshness', sa.String(length=16), nullable=False),
    sa.Column('prev_close', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_symbol_anchor',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('anchor_at', sa.DateTime(), nullable=False),
    sa.Column('anchor_price', sa.Float(), nullable=False),
    sa.Column('anchor_adj', sa.Float(), nullable=False),
    sa.Column('anchor_snapshot_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'symbol')
    )
    op.create_table('verdicts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('computed_for_anchor', sa.DateTime(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('epistemic', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=32), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot_price', sa.Float(), nullable=False),
    sa.Column('snapshot_adj', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'snapshot_id', name='uq_verdict_snapshot')
    )
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verdicts_snapshot_id'), ['snapshot_id'], unique=False)
        batch_op.create_index('ix_verdicts_user_symbol', ['user_id', 'symbol'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol'], ['symbols.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_items')
    with op.batch_alter_table('verdicts', schema=None) as batch_op:
        batch_op.drop_index('ix_verdicts_user_symbol')
        batch_op.drop_index(batch_op.f('ix_verdicts_snapshot_id'))

    op.drop_table('verdicts')
    op.drop_table('user_symbol_anchor')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    op.drop_table('quotes')
    op.drop_table('daily_bars')
    with op.batch_alter_table('corporate_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_events_symbol'))

    op.drop_table('corporate_events')
    op.drop_table('users')
    op.drop_table('trading_days')
    op.drop_table('symbols')
    op.drop_table('indices')
    op.drop_table('index_bars')
    # ### end Alembic commands ###
